---
Parameters:
  VpcCidr:
    Description: Please enter IP range (CIDR notation) for this VPC
    Default: 10.0.0.0/16
    Type: String

  PublicSubnetOneCidr:
    Description: Please enter IP range (CIDR notation) for Public Subnet 1
    Default: 10.0.1.0/24
    Type: String

  PrivateSubnetOneCidr:
    Description: Please enter IP range (CIDR notation) for Private Subnet 1
    Default: 10.0.21.0/24
    Type: String




Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label: 
          default: "Network Configuration"
        Parameters:
          - VpcCidr
          - PublicSubnetOneCidr
          - PrivateSubnetOneCidr
    
    ParameterLabels:
      VpcCidr: 
        default: VPC IP Range CIDR
      PublicSubnetOneCidr: 
        default: Public Subnet IP Range CIDR
      PrivateSubnetOneCidr: 
        default: Private Subnet IP Range CIDR




Resources:

  # VPC

  cpVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: 'true'
      EnableDnsSupport: 'true'
      InstanceTenancy: "default"
      Tags:
        -
          Key: "Name"
          Value: "cfnpractice-vpc-sample"


  # PUBLIC VPC NETWORK RESOURCES

  cpIgw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        -
          Key: "Name"
          Value: "cfnpractice-igw-sample"

  cpVpcGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref cpIgw
      VpcId: !Ref cpVpc

  cpPublicSubnetOne:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: !Ref PublicSubnetOneCidr
      MapPublicIpOnLaunch: True
      VpcId: !Ref cpVpc
      Tags:
        -
          Key: "Name"
          Value: "cfnpractice-subnet-public-one"

  cpVpcPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref cpVpc
      Tags:
        -
          Key: "Name"
          Value: "cfnpractice-main-route-table"

  cpIgwOutgoingRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref cpIgw
      RouteTableId: !Ref cpVpcPublicRouteTable

  cpPublicSubnetOneRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref cpVpcPublicRouteTable
      SubnetId: !Ref cpPublicSubnetOne


  #NAT - VPC NETWORK RESSOURCES FOR PRIVATE SUBNET PLACED IN PUBLIC SUBNET

  cpNat1EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  cpNatGateway1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt cpNat1EIP.AllocationId
      SubnetId: !Ref cpPublicSubnetOne
      Tags:
        -
          Key: "Name"
          Value: "cfnpractice-nat-gateway-one"


  # PRIVATE VPC NETWORK RESOURCES

  cpPrivateSubnetOne:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1a
      CidrBlock: !Ref PrivateSubnetOneCidr
      MapPublicIpOnLaunch: False
      VpcId: !Ref cpVpc
      Tags:
        -
          Key: "Name"
          Value: "cfnpractice-subnet-private-one"

  cpVpcPrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref cpVpc
      Tags:
        -
          Key: "Name"
          Value: "cfnpractice-private-route-table"

  cpDefaultPrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref cpNatGateway1
      RouteTableId: !Ref cpVpcPrivateRouteTable

  cpPrivateSubnetOneRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref cpVpcPrivateRouteTable
      SubnetId: !Ref cpPrivateSubnetOne